### ISSUE TITLE
TGSGapCandidate 'std::out_of_range'   what():  map::at

### ISSUE THREAD

**Issue by lurebgi** [BGI-Qingdao/FABuLOUS#4]
Hi,

It failed at step 2.2. This is my command:
`/scratch/luohao/software/FABuLOUS/FABuLOUS.sh --scaff chr.fa --reads <(cat /proj/luohao/parakeet/data/*.fasta) --output chr --racon /apps/racon/1.3.0/bin/racon  --tgstype pb --thread 32 --chunk 10`

> TGSGapCandidate	INFO	CET	2109/11/27	2:35:42	:	LoadPAF finish. used wall clock : 1125 seconds, cpu time : 1029.380005 seconds
> TGSGapCandidate	INFO	CET	2109/11/27	2:35:42	:	LoadScaffInfo start now ...
> TGSGapCandidate	INFO	CET	2109/11/27	2:35:49	:	LoadScaffInfo finish. used wall clock : 7 seconds, cpu time : 6.340000 seconds
> TGSGapCandidate	INFO	CET	2109/11/27	2:35:49	:	ParseAllGap start now ...
> terminate called after throwing an instance of 'std::out_of_range'
>   what():  map::at

I do not have this problem if I use a single fasta file instead of <(cat /proj/luohao/parakeet/data/*.fasta)

**Comment by cchd0001** [comment]
yes , current version only support  single fasta file .
